/**
 * Auto-generated route definitions
 * DO NOT EDIT - This file is generated by scripts/generate-routes.ts
 * Run: pnpm run generate:routes
 */

export const routes = {
  brands: {
    path: '/admin/brands' as const,
    params: {} satisfies {},
    search: {} satisfies { page?: string; search?: string; sort?: string },
  },
  brandsIdDetail: {
    path: '/admin/brands/[id]' as const,
    params: {} satisfies { id: string },
    search: {} satisfies { tab?: string },
  },
  brandsIdIddDetail: {
    path: '/admin/brands/[id]/[idd]' as const,
    params: {} satisfies { id: string; idd: string },
    search: {} satisfies {},
  },
  dashboard: {
    path: '/admin/dashboard' as const,
    params: {} satisfies {},
    search: {} satisfies { page?: string; filter?: string },
  },
  home: {
    path: '/admin/home' as const,
    params: {} satisfies {},
    search: {} satisfies {},
  },
  settings: {
    path: '/admin/settings' as const,
    params: {} satisfies {},
    search: {} satisfies { section?: string },
  },
} as const;

export type RouteId = 'brands' | 'brandsIdDetail' | 'brandsIdIddDetail' | 'dashboard' | 'home' | 'settings';

// Explicit type definitions for each route
// This ensures strict type checking - no number/string coercion
export type RouteParamsMap = {
  brands: {};
  brandsIdDetail: { id: string };
  brandsIdIddDetail: { id: string; idd: string };
  dashboard: {};
  home: {};
  settings: {};
};

export type RouteSearchMap = {
  brands: { page?: string; search?: string; sort?: string };
  brandsIdDetail: { tab?: string };
  brandsIdIddDetail: {};
  dashboard: { page?: string; filter?: string };
  home: {};
  settings: { section?: string };
};

// Path to RouteId mapping for type inference
export type RoutePathToId = {
  '/admin/brands': 'brands';
  '/admin/brands/[id]': 'brandsIdDetail';
  '/admin/brands/[id]/[idd]': 'brandsIdIddDetail';
  '/admin/dashboard': 'dashboard';
  '/admin/home': 'home';
  '/admin/settings': 'settings';
};

// Type helpers that use the explicit type maps
export type RouteParams<T extends RouteId> = RouteParamsMap[T];
export type RouteSearch<T extends RouteId> = RouteSearchMap[T];
export type RoutePath<T extends RouteId> = typeof routes[T]['path'];

// Union of all route paths (for use in TypedLink)
// This is the union of all path strings from the routes object
export type RoutePathUnion = 
  | '/admin/brands'
  | '/admin/brands/[id]'
  | '/admin/brands/[id]/[idd]'
  | '/admin/dashboard'
  | '/admin/home'
  | '/admin/settings';
